import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// components
import AppBar from "@/components/appBar";
// context
import { NavContextProvider } from "@/context/navContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gradient-to-br from-[#f0f] to-[#00f] h-screen `}
      >
        <NavContextProvider>
          <AppBar />
        </NavContextProvider>

        {children}
      </body>
    </html>
  );
}
